### ISSUE TITLE
Concept for expressing reputation policy & data

### ISSUE THREAD

**Issue by BitcoinErrorLog** [BitcoinAndLightningLayerSpecs/lsp#10]
"name": "reputation" 
		"repsystem": "https://fulmo.org/bos-score.html" 
		"ratings": "https://fulmo.org/bos-score.csv"" 

The "repsystem" label and values could be bikeshed in that instead of URLs, there could be an ID # system and resource looking up the specs for any registered reputation system...

The "ratings" would be a list of all ratings the LSP currently has available. If the rep system uses cryptographically signed ratings, then this list could include ratings from any peer about any other peer, as they are all verifiable. 

Peers could check for updates to the ratings list and add new ratings to the list after each order, or channel close, or any reason they want that fits the chosen reputation system.

This is the most basic reputation API I could think of. You simply share which system you use, and any ratings you want to share that abide by that system. 

Next elaboration might be to support expressing multiple systems and multiple lists, then map schemas and weightings for schemas, systems, and peers. (web of trust)

**Comment by aljazceru** [comment]
@BitcoinErrorLog would you have separate schema for reputation, or would you nest that under existing policies

**Comment by aljazceru** [comment]
closing as its obsolete/implemented elsewhere
