### ISSUE TITLE
LSPS1: Funding confirms within blocks

### ISSUE THREAD

**Issue by ErikDeSmedt** [BitcoinAndLightningLayerSpecs/lsp#112]
The `funding_confirms_within_blocks` should be a `u8`. This implies `0 <= funding_confirms_within_blocks <= 255`.
 
The default-value used by the client in `balance-of-satoshi` is 288 blocks.
This means the client gives the server approximately 48 hours to ensure the funding the transaction is confirmed.

I believe this default is reasonable but not spec-compliant.
- Should we change the data-type to `u16` instead?

Edit:: 255 instead of 256

**Comment by SeverinAlexB** [comment]
ACK
