### ISSUE TITLE
GET channel request spec should specify possible values for "state" enum string

### ISSUE THREAD

**Issue by dannydeezy** [BitcoinAndLightningLayerSpecs/lsp#15]
In the response of the GET channel request, it is unclear what the possible values for `state` should be.

I suggest two states:
- `PENDING` (channel has been requested but the open has not been initiated yet. it may be none, partially, or fully paid for at this point, which the user can deduce from the `amount_paid` variable)
- `OPEN_INITIATED` (the channel opening transaction has been broadcast. provides no info whether it has confirmed or is active yet)

thoughts?

**Comment by dannydeezy** [comment]
these two states are intentionally broad to limit complexity for implementing state updates on the LSP side

**Comment by dannydeezy** [comment]
but happy to consider more granular states if people want that

**Comment by BitcoinErrorLog** [comment]
My instinct is more granular, like PAID, PARTIAL_PMT, REFUNDED, FAILED, RETRYING, or such... but I defer to our actual node admins.

**Comment by SeverinAlexB** [comment]
Proposal. Please let me know if you are missing something or you disagree with any states:

| State          	| Description                                                                           	|
|----------------	|---------------------------------------------------------------------------------------	|
| TO_BE_PAID     	| When the order has been created but the user hasn't paid yet.                         	|
| PENDING        	| Order is paid but the channel has not been opened yet.                                	|
| OPEN_INITIATED 	| Channel broadcast transaction is in the mempool. 0conf might skip directly to OPENED. 	|
| OPENED         	| Channel is open and has the necessary block confirmations.                            	|
| FAILED         	| Any error. For example, the LSP couldn't connect to the target node.                  	|
| REFUNDED       	| Payment has been refunded.                                                            	|
| OFFER_EXPIRED  	| Order has not been paid and offer has therefore expired.                              	|

**Comment by dannydeezy** [comment]
> Proposal. Please let me know if you are missing something or you disagree with any states:
> 
> State	Description
> TO_BE_PAID	When the order has been created but the user hasn't paid yet.
> PENDING	Order is paid but the channel has not been opened yet.
> OPEN_INITIATED	Channel broadcast transaction is in the mempool. 0conf might skip directly to OPENED.
> OPENED	Channel is open and has the necessary block confirmations.
> FAILED	Any error. For example, the LSP couldn't connect to the target node.
> REFUNDED	Payment has been refunded.
> OFFER_EXPIRED	Order has not been paid and offer has therefore expired.

these look great to me. only nit is I think we could come up with a cleaner name for `TO_BE_PAID`

**Comment by SeverinAlexB** [comment]
> these look great to me. only nit is I think we could come up with a cleaner name for `TO_BE_PAID`, maybe `CREATED` ?

Sure, let it be `CREATED`. Let's shortly discuss this on our next LSP call in case somebody else has an input. Otherwise, I think this can be merged.

**Comment by SeverinAlexB** [comment]
#16
