### ISSUE TITLE
Spec is missing

### ISSUE THREAD

**Issue by TheBlueMatt** [BitcoinAndLightningLayerSpecs/lsp#19]
Is there a spec somewhere that is being worked on? So far I see a list of parameters, but there is no details or document describing how/where to use them. For example, there are parameters listed to, presumably an HTTP POST endpoint at /lsp/channel, but there's no indication of where to put them - is the body expected to be JSON or something else? There is no human-readable text explaining what a server responding to such a request has to do, only some fields they should (must?) include in the reply. Amounts are numbers, but..in what denomination, and how are precision errors handled? More importantly, what is the "fee", is it something paid explicitly? Is it something taken out of the first HTLC? When can I expect the channel to be opened, and do I get an option for how the fee is paid, etc.

**Comment by ZmnSCPxj-jr** [comment]
Given that we have decent LSPS0, LSPS1, and LSPS2 specs already merged in, can we close this issue?
