### ISSUE TITLE
Client Push Notification Webhook Registration

### ISSUE THREAD

**Issue by ZmnSCPxj-jr** [BitcoinAndLightningLayerSpecs/lsp#28]
As mildly discussed in the telegram group, clients running on mobile are likely to be put to sleep and have all connections killed.  This prevents the LSP from contacting the client in case it wants to do some action with the client.

Mobile OSs generally provide a "push notification" service, where an application developer runs some server which delivers notifications to the OS developer server, which then contacts the mobile device to let the mobile OS put a notification on the mobile device and which would wake up the application if the user selects the notification.

Generally, such notifications need a key from the application developer.

For a client application to be able to usefully connect to any LSP, the LSP should be able to contact the client for some events.  By Dependency Inversion Principle, both the mobile client and the LSP should rely on some abstraction that lets *any* LSP send a push notification to *any* mobile client, without tying a particular LSP and client together for push notifications.

The scheme is that the mobile client developer also runs a webserver with a webhook.  The client then registers the webhook with its LSP (including an identifier for the exact mobile device to push to in the `GET` parameters, any authorization from the client that the LSP is allowed to push notifications at it, etc.), and the LSP can then `POST` the webhook and send the reason for the notification, such as:

1.  The client can receive a payment.
2. The client has not been sending or receiving via the LSP, and the LSP wants to recover its liquidity from the client.
3. The LSP wants to change feerates, such as Lightning forwarding feerates or other auto-management feerates.
4. The LSP wants to stop providing service to the client.

Of note is that it is the client *developers* who have to run an HTTPS server, and the client need not have HTTPS client capability.

Open questions:

* How to ensure that replay attacks are not possible?  Is HTTPS enough?
* How best to authenticate the LSP is really the one `POST`ing to the webhook?

**Comment by SeverinAlexB** [comment]
We (Bitkit/Synonym) team discussed this some days ago. I like the webhook approach. I did write a webhook system from scratch before so I can write up an `auth` and `replay attack prevention` proposal.

Will do so as soon as I caught up with reviewing your other contributions (might take some weeks).
