### ISSUE TITLE
Hard to reference LSPS0 common schema

### ISSUE THREAD

**Issue by SeverinAlexB** [BitcoinAndLightningLayerSpecs/lsp#40]
I tried to reference the [LSPS0 on-chain fee rates](https://github.com/BitcoinAndLightningLayerSpecs/lsp/blob/main/LSPS0/common-schemas.md#on-chain-feerates) type in LSPS1. This is very hard though as each type doesn't have a short name.

I suggest defining a short name for each type. For example: On-chain fee rates could be of type `onchain_fee` and therefore be references in other specs as `LSPS0.onchain_fee`.

Any other suggestions?

**Comment by ZmnSCPxj-jr** [comment]
Looks OK to me.

**Comment by ZmnSCPxj-jr** [comment]
This seems to be done?  OK to close?

**Comment by SeverinAlexB** [comment]
Yes
