### ISSUE TITLE
Topics In-person Meetup 2024

### ISSUE THREAD

**Issue by tnull** [BitcoinAndLightningLayerSpecs/lsp#71]
This is a placeholder issue to collect topics that should be discussed as part of the upcoming in-person meetup.

**Comment by SeverinAlexB** [comment]
- LSPS4 in general
- Swap api

I will extend this list as we get closer to the meetup.

**Comment by ErikDeSmedt** [comment]
I would like to discuss implementations as well.

**Comment by BitcoinErrorLog** [comment]
LSP Watchtower services & spec - we all need this and we all need 3rd parties to host them

**Comment by ZmnSCPxj-jr** [comment]
* LSPS0 Finalization
* LSPS1 Finalization (maybe)
* LSPS2 Finalization (maybe)

**Comment by SeverinAlexB** [comment]
Can we close this?
