### ISSUE TITLE
LSPS1 design questions + improvement proposals

### ISSUE THREAD

**Issue by ErikDeSmedt** [BitcoinAndLightningLayerSpecs/lsp#73]
I've been reading the LSPS1-spec in some more detail and have a few questions and improvement proposals.

## Questions
- [x] How quick should a LSP-server open a channel?
  After receiving payment an LSP-server has to open the channel and pay the associated transaction fee. 
  To save costs an LSP might try to bundle these channel opening transactions (e.g: open all channels once every day).
  This is disadvantageous for the client who purchases a 0conf channel and wants to use it immediately.
  How to approach this issue?

- [ ] The field `minimum_onchain_payment_confirmations` in the options has a relative called `onchain_block_confirmations_required` in the payment object. The field `min_onchain_payment_size_sat` has no such relative.
   - Should we add a `min_onchain_payment_size_sat` in the payment-object?
     In my opinion an LSP should be allowed to increase the `min_onchain_payment_size_sat` at any-time.
     However, it should not affect any pending payments.
     We can achieve this by having a different value in the `payment`-struct vs the `options`-struct.

## Improvement proposals 

- [ ] The json-example representing the response to `lsps1.order` misses the `minimum_fee_for_0conf`.
  **Merge** https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/72)
- [ ] Inconsistent naming of `onchain_block_confirmations_required` vs `required_onchain_block_confirmations`.
  I propose to standardize on `min_onchain_payment_confirmations`.
  I would also rename `lsps1.options.minimum_onchain_payment_confirmations` to `min_onchain_payment_confirmations`
  **Merge** https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/74
- [ ] Some fields are prefixed with `minimum` and other with `min`. I fail to discover a semantic difference for when to use what.  I propose to make it consistent and use `min` everywhere because it is the shortest.
**Merge** https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/74

**Comment by SeverinAlexB** [comment]
> How quick should a LSP-server open a channel?

From the LSPS1:

>> MUST use a high enough on-chain fee rate to ensure the funding transaction confirms within `confirms_within_blocks` after the client paid the order.

> > - MAY open channels in batches, opening multiple channels in one transaction.
>>  - In this case, the LSP MUST still ensure that the funding transaction gets confirmed after a maximum of `confirms_within_blocks` after the client payment completed.

So whatever you do, if you batch or not, the channel funding tx MUST confirm after x blocks after the client paid.

> To save costs an LSP might try to bundle these channel opening transactions (e.g: open all channels once every day).
This is disadvantageous for the client who purchases a 0conf channel and wants to use it immediately.

Batching turbo channel is very difficult to do and I don't think it is realistic in practice.

---

> The field minimum_onchain_payment_confirmations in the options has a relative called onchain_block_confirmations_required in the payment object. The field min_onchain_payment_size_sat has no such relative.

I don't think we need this additional field. If `order_total_sat` is higher than `min_onchain_payment_size_sat` then the LSP will supply a `payment. onchain_address` field that indicates that onchain payments are activated. This way, even though the LSP changes `min_onchain_payment_size_sat` previous order with lower number of sats can still pay onchain.

---

>The json-example representing the response to lsps1.order misses the minimum_fee_for_0conf.
Merge https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/72)

Approved by me

---

> Inconsistent naming of onchain_block_confirmations_required vs required_onchain_block_confirmations.
I propose to standardize on min_onchain_payment_confirmations.
I would also rename lsps1.options.minimum_onchain_payment_confirmations to min_onchain_payment_confirmations

That is an unfortunate blunder. Let's do this.

---

> Some fields are prefixed with minimum and other with min. I fail to discover a semantic difference for when to use what. If propose to make it consistent and use min everywhere because it is the shortest.

Let's do it.

**Comment by ErikDeSmedt** [comment]
@SeverinAlexB : Thanks for the quick review. I'll create the associated MR's tomorrow.

I don't fully agree on the `min_onchain_payment` approach. 
It is reasonable for the LSP-server to provide an `onchain_address` even if `order_total_fee < min_onchain_payment_size_sat`.
In that case the client can either pay `order_total_fee` using lightning or `min_onchain_payment_size_sat` onchain.
This behavior is useful for clients that have bitcoin but don't have a lightning channel yet.

**Comment by SeverinAlexB** [comment]
I do not understand. If `order_total_fee` is lower than `min_onchain_payment_size_sat` then the LSP does not want to be paid onchain because `order_total_fee` is too low for an onchain payment. I do not understand your exception here.

**Comment by SeverinAlexB** [comment]
IMO, `min_onchain_payment_size_sat` will be mostly used as dust protection. If the fees are 100sat/vbyte (fee rate 100 * dust limit 294sat = 29'400sat) and the channel open fee is 2000sat, it does not make any sense to provide an address pay onchain.

**Comment by ErikDeSmedt** [comment]
Look at it from the client perspective.

The client doesn't have an open channel yet and can only pay onchain.
The client requests a channel to the server
- **Scenario A**: The server does not provide an onchain address because  `fee_order_total_sat` < `min_onchain_payment_size_sat`. The client cannot pay and is stuck. 
- **Scenario B**: The server includes `min_onchain_payment_size_sat` and an onchain address. The client can pay `min_onchain_payment_size_sat` to get a channel.

The server could also prefer scenario B. The server can set `min_onchain_payment_size_sat` sufficiently high.
