### ISSUE TITLE
LSPS2: (Re-)consider dropping `no-MPP+var-invoice` mode

### ISSUE THREAD

**Issue by tnull** [BitcoinAndLightningLayerSpecs/lsp#77]
I think we discussed this before, but it came to my attention again since I'm currently implementing LSPS2 client-side support in LDK Node:

LSPS2 currently offers two modes: `MPP+fixed-invoice` and  `no-MPP+var-invoice`. In the latter, it allows the client to leave out the optional `payment_size_msat` parameter and 'simply' lets the LSP forward the first HTLC it sees, independently of its amount.

However, this suffers from several pitfalls:

1) While the client can check the parameters based on the proportional fee beforehand, it can't compute the exact channel opening fee beforehand and will only learn how much the LSP deducted after the channel has been opened and the HTLC has to be claimed. It is now stuck between two bad choices: 
    a) always claim the HTLC, irrespective of how much fee the LSP deducted, given there is no maximum limit fee defined.
    b) only claim the HTLC if the LSP deducted less than a pre-configured amount. This leads to the client withholding the preimage and 'cheat' the LSP based on this arbitrary client-side parameter.
2) A variant would be for the client to compute the maximal possible opening fee based on `max_payment_size_msat` after receiving the `get_info` response and cancel the flow if it exceeds an arbitrary set limit. The resulting maximum fee might be huge and waaaay too large for a user only expecting a small/medium sized variable-amount payment. The user therefore is again stuck between accepting high 'risk'  (i.e. ~unlimited fees taken by the LSP) or arbitrarily failing the flow.
3) It is currently not (clearly) spec'ed that the LSP SHOULD check the variably sized HTLC against `{min,max}_payment_size_msat`. This leaves some ambiguity regarding when it is expected that an LSP would fail the HTLC. Since only the payer will be notified of failing HTLCs, the client won't receive any feedback as to why the channel open failed (although, this is of course a general issue of this flow).
4) Having two modes introduces significant complexity on both client and server side. Given that LSPS4 should allow us to solve this use case 'properly', we might want to keep LSPS2 as simple as possible.

I therefore would like to raise the topic again and suggest that we at least discuss once more whether we really need the `no-MPP+var-invoice` mode in LSPS2, and if it wouldn't be preferable to drop this mode for the sake of simplicity from the LSPS2 spec. LSPS4 should then solve this issue more thoroughly by forwarding the HTLCs to the client, allowing it to decide based on actual values.

**Comment by ErikDeSmedt** [comment]
I agree with the sentiment of simplifying LSPS2.

However, I fail to understand how `no-MPP+var-invoice` causes the problem you describe. To my understanding the fees are fully negotiated in advance and I don't see how surprises can occur.

When the client receives the HTLC, they can see `payment_size_msat` and compute agreed upon `opening_fee`. The client only provides the pre-image if the `opening_fee` matches the amount the LSP-server is withholding from the payment.

**Comment by ErikDeSmedt** [comment]
```
Right, but this is currently considered cheating
```

No it's not. The spec only requires clients to accept the payment forwards if the `opening_fee` is computed fairly. 

https://github.com/BitcoinAndLightningLayerSpecs/lsp/blob/d07cbb0bcdc1942c4970e4a2ac46f87c63dbdf33/LSPS2/README.md?plain=1#L928-L932
